const images = {
  logoFull: require("./logofull.png"),
  logo: require("./logo.png"),
  banner: require("../img/banner.png"),
  signupBanner: require("../img/signup.png"),
  googleMono: require("../img/google_mono.png"),
  google: require("../img/google.png"),
  twitterMono: require("../img/twitter_mono.png"),
  facebook: require("../img/facebook.png"),
  twitter: require("../img/twitter.png"),
  dottedBg: require("../img/dottedbg.png"),
  mouse1: require("../img/mouse1.png"),
  steelseries: require("../img/steelseries.png"),
  logitech: require("../img/logitech.png"),
  razer: require("../img/razer.png"),
  alienware: require("../img/alienware.png"),
  dell: require("../img/dell.png"),
  rog: require("../img/rog.png"),
  asus: require("../img/asus.png"),
  corsair: require("../img/corsair.png"),
  hyperx: require("../img/hyperx.png"),
  logowhite: require("../img/logo_white.png"),
  logoFullwhite: require("../img/logofull_white.png"),
  hyperxcloud: require("../img/hyperxcloud.png"),
  corsairk70: require("../img/corsairk70.png"),
  microphone: require("../img/microphone.png"),
  rogstrig: require("../img/rogstrig.png"),
  g733: require("../img/g733.png"),
  mouse2: require("../img/mouse2.png"),
  webcam: require("../img/webcam.png"),
  building: require("../img/building.png"),
  about: require("../img/about.png"),
  aboutTitle: require("../img/abouttitle.png"),
  mailbox: require("../img/mailbox.png"),
  reactjs: require("../img/reactjs.png"),
  tailwindcss: require("../img/tailwindcss.png"),
  nodejs: require("../img/nodejs.png"),
};

export default images;